import React, { useState } from 'react';
import { Download, FileText, Check, Loader2, ChevronDown } from 'lucide-react';

/**
 * ExportReportButton – Compiles the session into a formatted clinical
 * summary and triggers a Markdown download. A PDF variant is also available
 * via browser print-to-PDF.
 */
const ExportReportButton = ({ session }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [exporting, setExporting] = useState(null); // null | 'md' | 'pdf'
  const [done, setDone] = useState(null);

  if (!session?.aiAnalysis) return null;

  const {
    summary = '',
    keyFindings = [],
    crossModalCorrelation = '',
    riskOrAnomalyAlerts = [],
    recommendedActions = [],
    confidenceScore = 95,
  } = session.aiAnalysis;

  const buildMarkdown = () => {
    const now = new Date().toLocaleString();
    const fileList = (session.files || [])
      .map((f) => `  - **${f.originalName}** (${f.fileCategory}, ${(f.size / 1024 / 1024).toFixed(2)} MB)`)
      .join('\n');

    return `# ${session.title || 'Multimodal Synthesis Report'}

> **Generated by MediOmni AI** · ${now}  
> **Domain:** ${session.domain || 'Healthcare'} · **Confidence Score:** ${confidenceScore}%

---

## 📋 Executive Synthesis

${summary}

---

## 🔗 Cross-Modal Correlation

${crossModalCorrelation}

---

## 🔍 Key Findings

${keyFindings.map((f, i) => `${i + 1}. ${f}`).join('\n')}

---

## ⚠️ Risks & Anomaly Alerts

${riskOrAnomalyAlerts.length > 0
  ? riskOrAnomalyAlerts.map((a) => `- 🚨 ${a}`).join('\n')
  : '- No critical risks or anomalies detected.'}

---

## ✅ Recommended Actions

${recommendedActions.map((r) => `- [ ] ${r}`).join('\n')}

---

## 📁 Ingested Artifacts

${fileList || '  - No files attached (prompt-only session)'}

---

*This report was generated by MediOmni AI using Google Gemini multimodal synthesis.*  
*It is intended for decision support only and must be verified by a licensed practitioner.*
`;
  };

  const downloadMarkdown = () => {
    setExporting('md');
    setTimeout(() => {
      const md = buildMarkdown();
      const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      const safeName = (session.title || 'mediomni-report')
        .replace(/[^a-zA-Z0-9\s-]/g, '')
        .replace(/\s+/g, '-')
        .toLowerCase();
      a.href = url;
      a.download = `${safeName}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setExporting(null);
      setDone('md');
      setIsOpen(false);
      setTimeout(() => setDone(null), 2500);
    }, 600);
  };

  const printAsPDF = () => {
    setExporting('pdf');
    setIsOpen(false);
    setTimeout(() => {
      const md = buildMarkdown();
      const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>${session.title || 'MediOmni Report'}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Inter', 'Segoe UI', sans-serif; padding: 40px; max-width: 820px; margin: 0 auto; color: #1a202c; line-height: 1.7; background: #F8FAFC; }
  h1 { color: #0284C7; font-size: 1.6rem; margin-bottom: 4px; }
  h2 { color: #0D9488; font-size: 1.1rem; margin-top: 2rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 4px; }
  blockquote { background: #f0fdf4; border-left: 4px solid #10b981; padding: 8px 16px; border-radius: 4px; color: #065f46; font-size: 0.85rem; }
  code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-size: 0.85em; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 24px 0; }
  li { margin-bottom: 4px; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<pre style="white-space:pre-wrap;font-family:inherit">${md}</pre>
</body>
</html>`;
      const win = window.open('', '_blank');
      win.document.write(html);
      win.document.close();
      win.print();
      setExporting(null);
      setDone('pdf');
      setTimeout(() => setDone(null), 2500);
    }, 500);
  };

  const triggerStyle = {
    background: done ? '#ECFDF5' : '#FFFFFF',
    border: done ? '1.5px solid #6EE7B7' : '1px solid #E2E8F0',
    color: done ? '#059669' : '#374151',
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
    borderRadius: '12px',
    padding: '7px 14px',
    fontSize: '12px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    whiteSpace: 'nowrap',
  };

  return (
    <div className="relative">
      {/* Main trigger */}
      <button
        onClick={() => setIsOpen((v) => !v)}
        style={triggerStyle}
        onMouseEnter={(e) => {
          if (!done) {
            e.currentTarget.style.background = '#F0F9FF';
            e.currentTarget.style.borderColor = '#BAE6FD';
            e.currentTarget.style.color = '#0284C7';
          }
        }}
        onMouseLeave={(e) => {
          if (!done) {
            e.currentTarget.style.background = '#FFFFFF';
            e.currentTarget.style.borderColor = '#E2E8F0';
            e.currentTarget.style.color = '#374151';
          }
        }}
      >
        {exporting ? (
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
        ) : done ? (
          <Check className="w-3.5 h-3.5" />
        ) : (
          <Download className="w-3.5 h-3.5" />
        )}
        <span>{done ? 'Exported!' : 'Export Report'}</span>
        {!done && !exporting && (
          <ChevronDown
            className={`w-3 h-3 transition-transform ${isOpen ? 'rotate-180' : ''}`}
          />
        )}
      </button>

      {/* Dropdown */}
      {isOpen && (
        <>
          <div className="fixed inset-0 z-30" onClick={() => setIsOpen(false)} />
          <div
            className="absolute right-0 top-full mt-2 z-40 w-56 overflow-hidden"
            style={{
              background: '#FFFFFF',
              border: '1px solid #E2E8F0',
              borderRadius: '14px',
              boxShadow: '0 8px 28px rgba(0,0,0,0.12)',
            }}
          >
            <div className="p-2 space-y-1">
              <button
                onClick={downloadMarkdown}
                className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl text-xs text-left transition-all"
                style={{ color: '#374151' }}
                onMouseEnter={(e) => (e.currentTarget.style.background = '#F0F9FF')}
                onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
              >
                <div
                  className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                  style={{ background: '#DBEAFE' }}
                >
                  <FileText className="w-3.5 h-3.5" style={{ color: '#0284C7' }} />
                </div>
                <div>
                  <p className="font-semibold" style={{ color: '#0F172A' }}>Download Markdown</p>
                  <p style={{ color: '#94A3B8' }}>Structured .md clinical summary</p>
                </div>
              </button>

              <button
                onClick={printAsPDF}
                className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl text-xs text-left transition-all"
                style={{ color: '#374151' }}
                onMouseEnter={(e) => (e.currentTarget.style.background = '#F0FDF4')}
                onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
              >
                <div
                  className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                  style={{ background: '#D1FAE5' }}
                >
                  <Download className="w-3.5 h-3.5" style={{ color: '#059669' }} />
                </div>
                <div>
                  <p className="font-semibold" style={{ color: '#0F172A' }}>Save as PDF</p>
                  <p style={{ color: '#94A3B8' }}>Print-to-PDF via browser dialog</p>
                </div>
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
};

export default ExportReportButton;
